### ISSUE TITLE
Improve DX error message for `scripts/apidoc/signature.ts`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1685]
### Clear and concise description of the problem

While running `pnpm run generate:api-docs` I got an error like this

```node
- nearbyGPSCoordinate
/home/shinigami/OpenSource/faker/scripts/apidoc/signature.ts:238
            (property.type as ReflectionType)?.declaration.signatures?.[0]
                                               ^

TypeError: Cannot read properties of undefined (reading 'signatures')
    at <anonymous> (/home/shinigami/OpenSource/faker/scripts/apidoc/signature.ts:238:48)
    at Array.map (<anonymous>)
    at analyzeParameterOptions (/home/shinigami/OpenSource/faker/scripts/apidoc/signature.ts:231:23)
    at <anonymous> (/home/shinigami/OpenSource/faker/scripts/apidoc/signature.ts:227:7)
    at Array.flatMap (<anonymous>)
    at analyzeParameterOptions (/home/shinigami/OpenSource/faker/scripts/apidoc/signature.ts:226:32)
    at analyzeParameter (/home/shinigami/OpenSource/faker/scripts/apidoc/signature.ts:210:22)
    at analyzeSignature (/home/shinigami/OpenSource/faker/scripts/apidoc/signature.ts:128:20)
    at processModuleMethod (/home/shinigami/OpenSource/faker/scripts/apidoc/moduleMethods.ts:77:18)
    at processModuleMethods (/home/shinigami/OpenSource/faker/scripts/apidoc/moduleMethods.ts:34:19)
```

### Suggested solution

Instead of `TypeError: Cannot read properties of undefined (reading 'signatures')` we should try to provide a message about what happend and why this error occurs

### Additional context

Currently the error is terrible DX and a potential contributor could decide to just stop working on a PR and we would loose potential contributions

**Comment by ST-DDT** [comment]
I'll have a look soon.
