### ISSUE TITLE
`internet.jwt()` fails on documentation website

### ISSUE THREAD

**Issue by xDivisionByZerox** [faker-js/faker#3285]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/faker-js/faker/blob/next/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/faker-js/faker/blob/next/CONTRIBUTING.md).
- [X] Read the [docs](https://fakerjs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/faker-js/faker/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Faker issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/faker-js/faker/discussions) or join our [Discord Chat Server](https://chat.fakerjs.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] I am willing to provide a PR.

### Describe the bug

When running `faker.internet.jwt()`  on our documentation site, you receive an runtime error:

```js
+esm:13 Uncaught TypeError: Unknown encoding: base64url
    at Uint8Array.Yi (+esm:13:5072)
    at Uint8Array.a [as toString] (+esm:13:5949)
    at ir (chunk-3QROWZCZ.js:1:5396)
    at kr.jwt (chunk-3QROWZCZ.js:1:18786)
    at <anonymous>:1:16
```

This might affect other browser environments as well (at least the ones using the same CDN).

### Minimal reproduction code

Go to https://fakerjs.dev and open the dev tools.

Run the following:

```js
await enableFaker();
faker.internet.jwt();
```

### Additional Context

Our [check for the existance of `Buffer`](https://github.com/faker-js/faker/blob/b390432626811d2af32086b16151bc4c55634c60/src/internal/base64.ts#L42) fails because the file (https://cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/+esm) loaded from the cdn includes a Buffer polyfill:

![image](https://github.com/user-attachments/assets/8c686f92-d9c2-4c05-bdd6-4d8dd0f46751)

### Environment Info

```shell
Tested in Microsoft Edge - Version 131.0.2903.63 (Offizielles Build) (64-Bit)
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

npm

**Comment by xDivisionByZerox** [comment]
Would be glad if someone can confirm this bug.

**Comment by sounmind** [comment]
Same with me.

![image](https://github.com/user-attachments/assets/07d957f8-68c8-477d-958a-7819509f94c0)

### Environment Info
Mac, Chrome: 131.0.6778.69 (Official Build) (arm64)

**Comment by ST-DDT** [comment]
I can confirm the error as well on Firefox For Windows.
But I'm unable to explain it.

**Comment by ST-DDT** [comment]
Looks like it's getting poly filled:

https://cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/+esm

- Search for `Buffer` (case sensitive+whole word)

```
/*!
 * The buffer module from node.js, for the browser.
 *
 * @author   Feross Aboukhadijeh <feross@feross.org> <http://feross.org>
 * @license  MIT
 */
```

https://github.com/feross/buffer

**Comment by ST-DDT** [comment]
- https://github.com/feross/buffer/pull/314
- https://github.com/feross/buffer/issues/309
- https://github.com/feross/buffer/issues/361

**Comment by xDivisionByZerox** [comment]
> Looks like it's getting poly filled:
> 
> [cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/+esm](https://cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/+esm)
> [...]

I already came to the same conclusion in the "Additional Context" section of the issue. Still, I'm unable to grasp **why** this happens, since we have zero runtime dependencies..

**Comment by xDivisionByZerox** [comment]
Might the bundling from JSDelivery cause trouble? You can see at the top of the `+esm` file:

```txt
/**
 * Bundled by jsDelivr using Rollup v2.79.1 and Terser v5.19.2.
 * Original file: /npm/@faker-js/faker@9.2.0/dist/index.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
[...]
```

I tried the mentioned original file. When I do `const { faker } = await import('https://cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/dist/index.js')` our documentation site I can use faker without problems.

**Comment by ST-DDT** [comment]
> I already came to the same conclusion in the "Additional Context" section of the issue. Still, I'm unable to grasp **why** this happens, since we have zero runtime dependencies..

Oh, I haven't seen that part.



> I tried the mentioned original file. When I do `const { faker } = await import('https://cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/dist/index.js')` our documentation site I can use faker without problems.

Should we replace our import references?

**Comment by xDivisionByZerox** [comment]
> Should we replace our import references?

I guess that would be the best to not rely on downstream implementations. 🤔

**Comment by ST-DDT** [comment]
> I guess that would be the best to not rely on downstream implementations. 🤔

Yeah. especially since it seems to be stuck for many months now.

**Comment by xDivisionByZerox** [comment]
I checked again. The advantage of the `+esm` import is that the original file import fires 78 requests to retrieve all the chunks to load faker. This is about 50% slower from my quick testing. Can you run some tests on your end as well? Don't forget to disable the browser cache in the dev tools tho.

**Comment by ST-DDT** [comment]
```ts
console.time("bundled")
await import("https://cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/+esm");
console.timeEnd("bundled")
console.time("original")
await import("https://cdn.jsdelivr.net/npm/@faker-js/faker@9.2.0/dist/index.js");
console.timeEnd("original")
```

Mostly:

> bundled: 710ms
> original: 976ms

Sometimes:

> bundled: 204ms
> original: 413ms

**Comment by ST-DDT** [comment]
We could push a single file build onto our website and use that instead of an external source (`docs/public/faker.js`).
That way we could even try new features from PRs in the previews.

Might be useful in combination with:

- https://github.com/faker-js/faker/issues/3287

**Comment by xDivisionByZerox** [comment]
> We could push a single file build onto our website and use that instead of an external source (docs/public/faker.js).
That way we could even try new features from PRs in the previews.

Lets discuss this issue on thursdays team meeting. Since this issue is only present on the website if you are using functions that call the internal base64-helpers, the scope of this bug is pretty limited. If you think this is more urgend, feel free to provide a PR with your suggestion of a  fix.

**Comment by matthewmayer** [comment]
looks like there may be a way to stop jsdelivr adding the Buffer polyfill:
https://github.com/jsdelivr/jsdelivr/issues/18263#issuecomment-1345357257

**Comment by ST-DDT** [comment]
Not urgent as no users have reported this error yet.

This might also affect users that bundle faker into production code for whatever reason and applying the partial polyfil. So the neat trick with node:buffer=false might be worth applying anyway.

I consider the browser self bundling a separate feature.

**Comment by ST-DDT** [comment]
**Team Decision**

- We will change our toBase64Url method, to always use `toBase64().replaceAll()` with a TODO comment pointing to the upstream issue

**Comment by matthewmayer** [comment]
This still occurs even on 9.4.0

https://fakerjs.dev/api/internet.html#jwt

**Comment by ST-DDT** [comment]
Here is another attempt at fixing this:

- #3400
