### ISSUE TITLE
faker.internet.password maximum call stack size exceeded

### ISSUE THREAD

**Issue by quinnturner** [faker-js/faker#474]
### Describe the bug

```
RangeError: Maximum call stack size exceeded
at f.number (node_modules@faker-js[/faker/dist/cjs/datatype.js:1:832]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6813]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
      at n (node_modules@faker-js[/faker/dist/cjs/internet.js:1:6909]())
```

### Reproduction

`faker.internet.password(10, false, null, '!Aa0')` triggered the error.

https://stackblitz.com/edit/faker-js-demo-pkgjot?file=index.ts

### Additional Info

Version: `6.0.0-alpha.6`

**Comment by quinnturner** [comment]
It looks like the implementation of `password` chokes on non-alphanumeric characters. I suggest either adding support for them or explicitly throwing an error. 👍🏻

**Comment by Shinigami92** [comment]
As a workaround for now, could you use `faker.internet.password(10, false, /\w/, '!Aa0')`?

**Comment by quinnturner** [comment]
Thanks for the response, @Shinigami92! My workaround that worked for my use case was simply:

`const password = "!Aa0" + faker.internet.password(6);`

**Comment by xDivisionByZerox** [comment]
Please assign me to this. I'll have a look and provide a solution.

**Comment by xDivisionByZerox** [comment]
Can this be closed? Should this be documented? Should `null` be a valid value to use the default `RegEx`?

**Comment by Shinigami92** [comment]
I think it's documented by TypeScript :thinking: 
So yeah, from my side we could close it. (count as invalid usage)
But let's here a second maintainers voice.

**Comment by quinnturner** [comment]
While understandably invalid, passing null instead of undefined resulting in an infinite loop is not _great_. I am fine either way, as my call broke the function's contract -> led to invalid behaviour.

**Comment by ST-DDT** [comment]
AFAICT we don't explicitly handle `null` anywhere in the API, so I don't consider it worth fixing.
( I would rather improve the password generation in general in v7)

**Comment by dandok** [comment]
password: faker.internet.password({
     length: 10,
     pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])/,
  })
this causes the same error as earlier discussed. is there a workaround for this?

**Comment by ST-DDT** [comment]
I suggest using [faker.helpers.fromRegExp](https://fakerjs.dev/api/helpers.html#fromregexp) instead.
